# Generated by Django 3.2 on 2022-02-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=50, verbose_name='Client Type')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='test', max_length=100, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.clientcategory', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Main contact First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Main Contact Last Name'),
        ),
    ]
