# Generated by Django 3.2 on 2022-02-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220205_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttype',
            old_name='category_type',
            new_name='client_type',
        ),
    ]
