# Generated by Django 3.2 on 2022-02-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_category_type_clienttype_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.clienttype', verbose_name='Type'),
        ),
    ]
