# Generated by Django 3.2 on 2022-02-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_client_client_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='clientcategory',
            options={'verbose_name': 'Client Industry', 'verbose_name_plural': 'Client Industries'},
        ),
        migrations.CreateModel(
            name='ClientTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=50, null=True, verbose_name='Telephone Number')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Telephone',
                'verbose_name_plural': 'Client Telephones',
            },
        ),
    ]
